services:
  - type: web
    name: textapp
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 1 --threads 100 --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.6"
      - key: RENDER
        value: "true"
      - key: SECRET_KEY
        generateValue: true
      - key: MONGO_URI
        sync: false
